dataset:
    data_dir: '/gpfs/CompMicro/Hummingbird/RawData/LiHao/20190829_Kazansky_BF'
    processed_dir: '/gpfs/CompMicro/Projects/waveorderData/Test/ReconstructOrderTest'
    samples: ['SMS_2019_0829_1639_1']
    positions: 'all'
    ROI: [820, 890, 300, 300] # [Ny_start, Nx_start, number_of_pixel_in_y, number_of_pixel_in_x]
    background: 'BG_2019_0829_1638_1' 

processing:
    output_channels: ['Brightfield_computed', 'Retardance', 'Orientation', 'Polarization', 'Phase2D', 'Phase3D']
    circularity: 'rcp'
    background_correction: 'Input'
    flatfield_correction: False
    n_slice_local_bg: all
    azimuth_offset: 0
    separate_positions: True
    
    use_gpu: True
    gpu_id: 0
    
    # parameters related specific to phase reconstruction
    pixel_size: 6.5    # in the unit of micrometer
    magnification: 20
    NA_objective: 0.55
    NA_condenser: 0.4
    n_objective_media: 1
    focus_zidx: 10     # index of the focused layer for the z stack
    
    # denoiser: either 'Tikhonov' or 'TV'
    phase_denoiser_2D: 'TV'
    
    # Tikhonov regularizer
    # 1.0e-3 should work generally when noise is low
    # if noise is higher raise an order of magnitude to see if the recon is better
    Tik_reg_abs_2D: 1.0e-3
    Tik_reg_ph_2D: 1.0e-3
    
    # TV parameter
    # rho_2D = 1 and itr_2D = 50 is generally good, no need to tune
    # TV_reg of value around 1e-4 is generally good
    # For more noisy data, raise TV_reg to enforce stronger denoising effect
    rho_2D: 1
    itr_2D: 50
    TV_reg_abs_2D: 1.0e-3
    TV_reg_ph_2D: 1.0e-5
    
    # denoiser: either 'Tikhonov' or 'TV'
    phase_denoiser_3D: 'Tikhonov'
    
    # Tikhonov regularizer
    # 1.0e-3 to 1.0e-4 should work generally when noise is low
    # if noise is higher raise an order of magnitude to see if the recon is better
    Tik_reg_ph_3D: 1.0e-3
    
    # TV parameter
    # rho_3D = 1.0e-3 and itr_3D = 50 is generally good, no need to tune
    # TV_reg of value around 5e-5 is generally good
    # For more noisy data, raise TV_reg to enforce stronger denoising effect
    rho_3D: 1.0e-3
    itr_3D: 50
    TV_reg_ph_3D: 5.0e-5
    
    # number of slices padded in each side of z stack 
    # to reduce periodic artifacts in z for 3D deconvolution
    # generally 3 to 5 should be enough
    pad_z: 5
    


plotting:
    normalize_color_images: True
    save_birefringence_fig: False
    save_stokes_fig: False
    save_polarization_fig: False
    save_micromanager_fig: False
    phase_2D_scaling: 1  # when scaling is 1, phase is plotted from -5 to 5 radian
    phase_3D_scaling: 1  # when scaling is 1, phase is plotted from -5 to 5 radian

